backoffice/babytouch/babytouch_data/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns('babytouch.babytouch_data.views',
    url(r'^sort/$', 'instance_sort', name='instance_sort'),
    url(r'^itemclass/$', 'itemclass_manage', name='itemclass_manage'),
    url(r'^itemclass/(?P<pk>[0-9A-Za-z._-]+)/$', 'itemclass_manage_single', name='itemclass_manage_single'),
    url(r'^crop/$', 'set_cropping_rectangle', name='set_cropping_rectangle'),
    url(r'^crop/(?P<instance_pk>[0-9A-Za-z._-]+)/$', 'set_cropping_rectangle', name='set_cropping_rectangle'),
    url(r'^thumbcrop/$', 'set_thumbnail_cropping_rectangle', name='set_thumbnail_cropping_rectangle'),
    url(r'^thumbcrop/(?P<instance_pk>[0-9A-Za-z._-]+)/$', 'set_thumbnail_cropping_rectangle', name='set_thumbnail_cropping_rectangle'),

    url(r'^itemclasssound/add/$', 'itemclasssound_add', name='itemclasssound_add'),
)

urlpatterns += patterns('babytouch.babytouch_data.api',
    url(r'^api/iteminstance/(?P<pk>[0-9A-Za-z._-]+)/enable/$', 'iteminstance_enable'),
    url(r'^api/iteminstance/(?P<pk>[0-9A-Za-z._-]+)/disable/$', 'iteminstance_disable'),
    url(r'^api/iteminstance/(?P<pk>[0-9A-Za-z._-]+)/set_as_main_instance/$', 'iteminstance_set_as_main_instance'),
    url(r'^api/iteminstance/(?P<pk>[0-9A-Za-z._-]+)/set_sound/$', 'iteminstance_set_sound'),
    url(r'^api/itemclass/(?P<pk>[0-9A-Za-z._-]+)/enable/$', 'itemclass_enable'),
    url(r'^api/itemclass/(?P<pk>[0-9A-Za-z._-]+)/disable/$', 'itemclass_disable'),
)

backoffice/babytouch/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # url(r'^$', 'babytouch.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('babytouch.babytouch_data.urls', namespace='babytouch')),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

backoffice/babytouch/babytouch_data/models.py
import os

from django.db import models
from django.core.files import File


class CommonDataModel(models.Model):

    class Meta:
        abstract = True

    appx_prefix = 'ms-appx:///DefaultContent/'

    id = models.CharField(max_length=128, primary_key=True, unique=True)
    title = models.CharField(max_length=256, default='')
    is_enabled = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def to_dict(self):
        return {
            'Id': self.id,
            'Title': self.title,
            'IsEnabled': self.is_enabled,
        }

    @staticmethod
    def remove_appx_prefix_from_uri(uri):
        if uri.startswith(CommonDataModel.appx_prefix):
            return uri[len(CommonDataModel.appx_prefix):]
        else:
            return uri

    @staticmethod
    def add_appx_prefix_to_uri(uri):
        return CommonDataModel.appx_prefix + uri

    def __unicode__(self):
        return '[%s] %s' % (self.id, self.title)


class Group(CommonDataModel):

    @classmethod
    def from_dict(cls, data):
        return Group(
            id=data['Id'],
            title=data['Title'],
            is_enabled=data.get('IsEnabled', True),
        )


class ItemClass(CommonDataModel):
    group = models.ForeignKey(Group)
    main_instance = models.OneToOneField('ItemInstance', null=True,
        related_name='class_where_iam_main')

    def to_dict(self):
        base = super(ItemClass, self).to_dict()
        base.update({
            'GroupId': self.group_id,
            'MainInstanceId': self.main_instance_id,
        })
        return base

    @classmethod
    def from_dict(cls, data):
        return ItemClass(
            id=data['Id'],
            title=data['Title'],
            is_enabled=data.get('IsEnabled', True),
            group_id=data['GroupId'],
            main_instance_id=data['MainInstanceId'],
        )

    def add_sound_from_file(self, filepath):
        sound = ItemClassSound(item_class=self)
        with open(filepath, 'rb') as fp:
            sound.sound = File(fp)
            sound.save()

        return sound


class ItemClassSound(models.Model):
    item_class = models.ForeignKey(ItemClass, related_name='sounds')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    sound = models.FileField(upload_to='Sounds')

    def filename(self):
        return os.path.basename(self.sound.path)

    def __unicode__(self):
        return '[%s] %s' % (self.item_class_id, self.filename())


class ItemInstance(CommonDataModel):
    item_class = models.ForeignKey(ItemClass, null=True, related_name='instances')
    sound = models.ForeignKey(ItemClassSound, null=True, related_name='instances')
    copyright = models.CharField(max_length=128, default='')

    # photo (original size)
    image = models.ImageField(upload_to='Images/unsorted', null=True, height_field='image_height', width_field='image_width')
    image_height = models.IntegerField(default=0)
    image_width = models.IntegerField(default=0)

    # thumbnail
    image_thumbnail = models.ImageField(upload_to='Thumbnails', null=True)
    thumbnail_crop_top = models.IntegerField(default=0)
    thumbnail_crop_left = models.IntegerField(default=0)
    thumbnail_crop_size = models.IntegerField(default=0)

    # crop rectangle info
    crop_rectangle_top = models.IntegerField(default=0)
    crop_rectangle_left = models.IntegerField(default=0)
    crop_rectangle_width = models.IntegerField(default=0)
    crop_rectangle_height = models.IntegerField(default=0)

    THUMBNAIL_WIDTH = 250

    def to_dict(self):
        base = super(ItemInstance, self).to_dict()
        base.update({
            'ClassId': self.item_class_id,
            'Copyright': self.copyright,
            'SoundUri': self.add_appx_prefix_to_uri(self.sound.sound.name) if self.sound else None,
            'ImageUri': self.add_appx_prefix_to_uri(self.image.name) if self.image else None,
            'ThumbnailUri': self.add_appx_prefix_to_uri(self.image_thumbnail.name) if self.image_thumbnail else None
        })
        return base

    @classmethod
    def from_dict(cls, data):
        return ItemInstance(
            id=data['Id'],
            title=data.get('Title', ''),
            is_enabled=data.get('IsEnabled', True),
            sound=ItemClassSound(item_class_id=data['ClassId'], sound=cls.remove_appx_prefix_from_uri(data.get('SoundUri', ''))),
            image=cls.remove_appx_prefix_from_uri(data.get('ImageUri', '')),
            item_class_id=data['ClassId'],
            copyright=data.get('Copyright', ''),
        )


class IMAGE_SCALE:
    SCALE_80 = 80
    SCALE_100 = 100
    SCALE_140 = 140
    SCALE_180 = 180

    SCALE_100_SIZE = (1366, 768)
    SCALE_140_SIZE = (1920, 1080)
    SCALE_180_SIZE = (2560, 1440)

    scales = (SCALE_80, SCALE_100, SCALE_140, SCALE_180)
    choices = [
        (SCALE_80, '80%'),
        (SCALE_100, '100%'),
        (SCALE_140, '140%'),
        (SCALE_180, '180%'),
    ]
    asset_sizes = {
        SCALE_100: SCALE_100_SIZE,
        SCALE_140: SCALE_140_SIZE,
        SCALE_180: SCALE_180_SIZE
    }


class ItemImage(models.Model):
    instance = models.ForeignKey(ItemInstance)
    image = models.ImageField(upload_to='Images/scaled', null=True)
    scale = models.IntegerField(choices=IMAGE_SCALE.choices)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

backoffice/babytouch/babytouch_data/forms.py
from django import forms
from .models import ItemInstance, ItemClass, ItemClassSound

class InstanceToClassMappingForm(forms.Form):
    item_class = forms.ModelChoiceField(ItemClass.objects.all())
    instances = forms.ModelMultipleChoiceField(ItemInstance.objects.all())


class CropForm(forms.ModelForm):

    class Meta:
        model = ItemInstance
        fields = ('crop_rectangle_top', 'crop_rectangle_left', 'crop_rectangle_width', 'crop_rectangle_height')


class ThumbnailCropForm(forms.ModelForm):

    class Meta:
        model = ItemInstance
        fields = ('thumbnail_crop_top', 'thumbnail_crop_left', 'thumbnail_crop_size')


class AddSoundForm(forms.ModelForm):

    class Meta:
        model = ItemClassSound
        fields = ('sound', 'item_class')
        widgets = {
            'item_class': forms.HiddenInput,
        }

backoffice/babytouch/babytouch_data/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count, F
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse

from .models import ItemInstance, ItemClass, IMAGE_SCALE
from .forms import InstanceToClassMappingForm, CropForm, ThumbnailCropForm, AddSoundForm


def instance_sort(request):
    if request.method == 'POST':
        form = InstanceToClassMappingForm(request.POST)
        if form.is_valid():
            item_class = form.cleaned_data['item_class']
            instances = form.cleaned_data['instances']
            instances.filter(item_class__isnull=True).update(item_class=item_class)
        else:
            print 'Form validation error occured', form.errors

    classes = ItemClass.objects.all().select_related().order_by('group__title', 'title')
    rarest_classes = (ItemClass.objects.all()
        .annotate(count_instances=Count('instances'))
        .order_by('count_instances')[:10])
    fullest_classes = (ItemClass.objects.all()
        .annotate(count_instances=Count('instances'))
        .order_by('-count_instances')[:10])
    instances = ItemInstance.objects.filter(item_class__isnull=True)
    context = {
        'classes': classes,
        'rarest_classes': rarest_classes,
        'fullest_classes': fullest_classes,
        'instances': instances,
    }
    return render(request, 'babytouch/sort.html', context)


def _set_cropping_rectangle(request, instance_pk=None, form_cls=None, initial_queryset=None, urlname=None, template_name=None):

    instances_without_cropping = initial_queryset
    if instance_pk is None:
        instances_pair = instances_without_cropping.order_by('pk')[:2]
        if len(instances_pair) == 2:
            instance, next_instance = instances_pair
        else:
            assert len(instances_pair) == 1
            instance, next_instance = instances_pair[0], None

    else:
        instance = ItemInstance.objects.get(pk=instance_pk)
        try:
            next_instance = instances_without_cropping.filter(pk__gt=instance_pk).order_by('pk')[0]
        except IndexError:
            next_instance = None

    if request.method == 'POST':
        form = form_cls(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            if next_instance is not None:
                return redirect(urlname, instance_pk=next_instance.pk)
    else:
        form = form_cls(instance=instance)

    context = {
        'instance': instance,
        'next_instance': next_instance,
        'crop_form': form,
        'instances_without_cropping_count': instances_without_cropping.count(),
        'IMAGE_SCALE': IMAGE_SCALE,
        'crop_urlname': urlname,
    }
    return render(request, template_name, context)


def set_cropping_rectangle(request, instance_pk=None):
    return _set_cropping_rectangle(request,
        instance_pk=instance_pk,
        form_cls=CropForm,
        initial_queryset=ItemInstance.objects.filter(crop_rectangle_width=0),
        urlname='babytouch:set_cropping_rectangle',
        template_name='babytouch/set_cropping_rectangle.html',
    )


def set_thumbnail_cropping_rectangle(request, instance_pk=None):

    initial_queryset = ItemInstance.objects.filter(item_class__main_instance__id=F('id'))

    if request.GET.get('show_all') is None:
        initial_queryset = initial_queryset.filter(thumbnail_crop_size=0)

    return _set_cropping_rectangle(request,
        instance_pk=instance_pk,
        form_cls=ThumbnailCropForm,
        initial_queryset=initial_queryset,
        urlname='babytouch:set_thumbnail_cropping_rectangle',
        template_name='babytouch/set_thumbnail_cropping_rectangle.html',
    )


def itemclass_manage(request):

    classes_queryset = (ItemClass.objects.all()
        .order_by('group__id', '-is_enabled')
        .select_related('main_instance', 'group', 'main_instance__sound')
        .prefetch_related('instances'))

    for item_class in classes_queryset:
        item_class.instances_enabled_count = len(filter(lambda instance: instance.is_enabled, item_class.instances.all()))

    context = {
        'classes': classes_queryset,
    }

    return render(request, 'babytouch/itemclass_manage.html', context)


def itemclass_manage_single(request, pk):
    item_class = get_object_or_404(ItemClass, pk=pk)

    instances = item_class.instances.select_related('sound').order_by('-is_enabled')
    instances_total_count = len(instances)
    instances_enabled_count = len(filter(lambda i: i.is_enabled, instances))

    available_sounds = item_class.sounds.all()

    add_sound_form = AddSoundForm(initial={'item_class': item_class})

    context = {
        'item_class': item_class,
        'available_sounds': available_sounds,
        'add_sound_form': add_sound_form,
        'instances': instances,
        'instances_enabled_count': instances_enabled_count,
        'instances_total_count': instances_total_count,
    }

    return render(request, 'babytouch/itemclass_manage_single.html', context)


@require_http_methods(["POST"])
def itemclasssound_add(request):
    f = AddSoundForm(request.POST)
    if f.is_valid():
        f.save()

    return redirect(itemclass_manage_single, pk=f.instance.item_class_id)

backoffice/babytouch/babytouch_data/templates/babytouch/itemclass_manage.html
{% extends "base.html" %}
{% load babytouch_tags %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        init_itemclass_list($(".babytouch__itemclass__item"));
    });
</script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="span9">
        <div class="row-fluid">
            {% for class in classes %}
                {% ifchanged class.group_id %}
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <h3>{{ class.group.title }}</h3>
                        </div>
                    </div>
                    <div class="row-fluid">
                {% endifchanged %}
                <div class="span3 babytouch__itemclass__item {% if not class.is_enabled %} babytouch__itemclass_disabled{% endif %}{% if class.instances_enabled_count > 4 %} babytouch__itemclass_full{% endif %}" data-class-id="{{ class.id }}">
                    <b class="babytouch__itemclass__title">{{ class.title }}</b>
                    <span class="babytouch__itemclass__counters">{{ class.instances_enabled_count }} / {{ class.instances.count }}</span>
                    <span class="babytouch__itemclass__controls">
                        <span class="babytouch__itemclass__controls__toggle-enabled"></span>
                    </span>

                    <a href="{% url "babytouch:itemclass_manage_single" pk=class.pk %}">
                        {% include "babytouch/thumbnail_snippet.html" with instance=class.main_instance %}
                    </a>
                    {% if class.main_instance.sound %}
                    <audio controls preload="none" class="babytouch__sound__controls">
                        <source src="{{ class.main_instance.sound.sound.url }}" type="{% get_media_type class.main_instance.sound.sound.url %}" />
                    </audio>
                    {% endif %}
                </div>

                {% if forloop.counter|divisibleby:4 %}
                </div><div class="row-fluid">
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

backoffice/babytouch/babytouch_data/templates/babytouch/itemclass_manage_single.html
{% extends "base.html" %}
{% load babytouch_tags %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        init_itemclass($(".babytouch__itemclass"));
    });
</script>
{% endblock %}

{% block content %}
<div class="row babytouch__itemclass" data-class-id="{{ item_class.id }}">
    <div class="span5">
        <h3>Sounds available:</h3>
        <ul class="babytouch__itemclass__sounds">
            {% for sound in available_sounds %}
                <li>
                    <div data-sound-id="{{ sound.pk }}" class="babytouch__sound">
                        <span class="babytouch__sound__filename">{{ sound.filename }}</span>
                        <audio controls preload="none" class="babytouch__sound__controls">
                            <source src="{{ sound.sound.url }}" type="{% get_media_type sound.sound.url %}" />
                        </audio>
                    </div>
                </li>
            {% empty %}
                <li>No sounds available.</li>
            {% endfor %}
        </ul>
        <div class="babytouch__add-sound">
            <form method="post" action="{% url "babytouch:itemclasssound_add" %}">{% csrf_token %}
                {{ add_sound_form.item_class }}
                {{ add_sound_form.sound }}
                <input type="submit" value="Add new sound" />
            </form>
        </div>
    </div>

    <div class="span9">
        <div class="row-fluid">
            <div class="span12">
                <h2>{{ item_class.title }} {{ instances_enabled_count }}/{{ instances_total_count }}</h2>
                (<a href="{% url "admin:babytouch_data_itemclass_change" item_class.id %}">admin</a>)
            </div>
        </div>
        <div class="row-fluid">
            {% for instance in instances %}
                <div class="span3 babytouch__itemclass__instance {% if instance.pk == item_class.main_instance_id %} babytouch__itemclass__instance_main{% endif %}{% if not instance.is_enabled %} babytouch__itemclass__instance_disabled{% endif %}" data-instance-id="{{ instance.id }}">
                    <span class="babytouch__itemclass__instance__controls">
                        <span class="babytouch__itemclass__instance__controls__toggle-enabled"></span>
                        <a href="{% url "admin:babytouch_data_iteminstance_change" instance.id %}" target="_blank"><span class="babytouch__itemclass__instance__controls__edit"></span></a>
                        <span class="babytouch__itemclass__instance__controls__set-as-main"></span>
                    </span>
                    {% include "babytouch/thumbnail_snippet.html" %}
                    {% if instance.sound %}
                    <div class="babytouch__sound">
                        <span class="babytouch__sound__filename">{{ instance.sound.filename }}</span>
                        <audio controls preload="none" class="babytouch__sound__controls">
                            <source src="{{ instance.sound.sound.url }}" type="{% get_media_type instance.sound.sound.url %}" />
                        </audio>
                    </div>
                    {% endif %}
                </div>
                {% if forloop.counter|divisibleby:4 %}
                </div><div class="row-fluid">
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

backoffice/babytouch/babytouch_data/templates/babytouch/set_cropping_rectangle.html
{% extends "base.html" %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        var crop = init_crop({{ instance.image_width }}, {{ instance.image_height }}, {
            aspect_ratio: 16 / 9,
            min_real_width: {{ IMAGE_SCALE.SCALE_100_SIZE.0 }},
            min_real_height: {{ IMAGE_SCALE.SCALE_100_SIZE.1 }},
            input_names: {
                top: "crop_rectangle_top",
                left: "crop_rectangle_left",
                width: "crop_rectangle_width",
                height: "crop_rectangle_height",
            },
            crop_rectangle: {
                top: {{ instance.crop_rectangle_top|default_if_none:"0" }},
                left: {{ instance.crop_rectangle_left|default_if_none:"0" }},
                width: {{ instance.crop_rectangle_width|default_if_none:"0" }},
                height: {{ instance.crop_rectangle_height|default_if_none:"0" }}
            }
        });
    })
</script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="span3">
        <h4>Instances left to crop: {{ instances_without_cropping_count }}</h4>
        <form method="POST" action="" class="babytouch__crop__form">{% csrf_token %}
            {{ crop_form.as_p }}
            <br/>
            <button type="submit" class="btn btn-primary">Set rectangle</button>
        </form>
        {% if next_instance %}
        <a href="{% url crop_urlname instance_pk=next_instance.pk %}">Next</a>
        {% else %}
        Done. <a href="{% url crop_urlname %}">Start again.</a>
        {% endif %}
    </div>
    <div class="span10">
        <div class="babytouch__crop__image-container">
            <img class="babytouch__crop__image-to-crop" src="{{ instance.image.url }}" />
            <div class="babytouch__crop__crop-rectangle"></div>
        </div>
    </div>
</div>
{% endblock %}

backoffice/babytouch/babytouch_data/templates/babytouch/set_thumbnail_cropping_rectangle.html
{% extends "babytouch/set_cropping_rectangle.html" %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        var crop = init_crop({{ instance.image_width }}, {{ instance.image_height }}, {
            aspect_ratio: 1,
            min_real_width: {{ instance.THUMBNAIL_WIDTH }},
            min_real_height: {{ instance.THUMBNAIL_WIDTH }},
            input_names: {
                top: "thumbnail_crop_top",
                left: "thumbnail_crop_left",
                width: "thumbnail_crop_size",
            },
            crop_rectangle: {
                top: {{ instance.thumbnail_crop_top|default_if_none:"0" }},
                left: {{ instance.thumbnail_crop_left|default_if_none:"0" }},
                width: {{ instance.thumbnail_crop_size|default_if_none:"0" }},
                height: {{ instance.thumbnail_crop_size|default_if_none:"0" }}
            }
        });
    })
</script>
{% endblock %}

backoffice/babytouch/babytouch_data/templates/babytouch/sort.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}jquery/multiselect/css/multi-select.css" />
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{{ STATIC_URL }}jquery/multiselect/js/jquery.multi-select.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var thumbnail_element = $(".babytouch__iteminstance__thumbnail");
        var form = $(".babytouch__sort-form");
        var multiselect = form.find('[name="instances"]');
        var class_select = form.find('[name="item_class"]');

        multiselect.multiSelect();

        thumbnail_element.click(function() {
            var instance_id = $(this).attr("data-instance-id");

            if ($(this).hasClass("selected"))
            {
                multiselect.multiSelect("deselect", instance_id);
            }
            else
            {
                multiselect.multiSelect("select", instance_id);
            }
            $(this).toggleClass("selected");
        });

        $(".babytouch__class-top__row").click(function() {
            var class_id = $(this).attr("data-class-id");
            class_select.val(class_id);
        });

    })
</script>
{% endblock %}

{% block content %}

<div class="row">
    <div class="span5">
        <div class="affix">
        <form method="post" action="" class="babytouch__sort-form">{% csrf_token %}
            <select name="item_class">
                {% regroup classes by group as grouped_classes %}
                {% for classgroup in grouped_classes %}
                <optgroup label="{{ classgroup.grouper.title }}">
                    {% for class in classgroup.list %}
                    <option value="{{ class.pk }}">{{ class.title }}</option>
                    {% endfor %}
                </optgroup>
                {% endfor %}
            </select>
            <br/>
            <select name="instances" size=20 multiple id="babytouch__instances__multiselect">
                {% for instance in instances %}
                <option value="{{ instance.pk }}">{{ instance.pk }}</option>
                {% endfor %}
            </select>
            <br/>
            <input class="btn" type="submit" value="Set class" />
        </form>

        <p>
        <h3>Top 10 rarest classes:</h3>
        <table class="table">
            <thead>
                <th>Instances</th>
                <th>Title</th>
                <th>Group</th>
            </thead>
            {% for class in rarest_classes %}
            <tr class="babytouch__class-top__row" data-class-id="{{ class.pk }}">
                <td>{{ class.count_instances }}</td>
                <td>{{ class.title }}</td>
                <td><a href="{% url "admin:babytouch_data_group_change" class.group_id %}">{{ class.group_id }}</a></td>
            </tr>
            {% endfor %}
        </table>
        </p>
        <p>
        <h3>Top 10 fullest classes:</h3>
        <table class="table">
            <thead>
                <th>Instances</th>
                <th>Title</th>
                <th>Group</th>
            </thead>
            {% for class in fullest_classes %}
            <tr>
                <td>{{ class.count_instances }}</td>
                <td>{{ class.title }}</td>
                <td><a href="{% url "admin:babytouch_data_group_change" class.group_id %}">{{ class.group_id }}</a></td>
            </tr>
            {% endfor %}
        </table>
        </p>
        </div>
    </div>
    <div class="span9">
        <h3>Unsorted images left: {{ instances|length }}</h3>
        <div class="row-fluid">
            {% for instance in instances %}
                {% include "babytouch/thumbnail_snippet.html" with cssclasses="span3 babytouch__iteminstance" %}
                {% if forloop.counter|divisibleby:4 %}
                </div><div class="row-fluid">
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

backoffice/babytouch/babytouch_data/templates/babytouch/thumbnail_snippet.html
<div class="{{ cssclasses }} babytouch__iteminstance__thumbnail" data-instance-id="{{ instance.id }}" data-class-id="{{ instance.item_class_id }}">
    <img src="{% if instance.image_thumbnail %}{{ instance.image_thumbnail.url }}{% else %}{{ instance.image.url }}{% endif %}" width="160px" title="{{ instance.title }}" />
</div>